### ISSUE TITLE
Mismatch between pip and repo

### ISSUE THREAD

**Issue by Donaschmi** [rhasspy/rhasspy-client#12]
Hi everyone.

I encountered the following error while performing some test with the TTS functionnality :
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 24: invalid start byte` 
throwed by:
`  File "/usr/local/lib/python3.9/site-packages/rhasspyclient/__init__.py", line 202, in text_to_speech
    return await response.text()`

I suspect that the issue might be that the return statement returns `text()` instead of the `read()` seen in the repo. I guess that the pip package is not up-to-date.

**Comment by koenvervloesem** [comment]
Indeed, thanks for the reminder.

@synesthesiam I tagged a new release, can you publish 1.1.1 to PyPI?
